# Generated by Django 2.2.7 on 2019-11-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('composer', models.CharField(max_length=50)),
                ('level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('salutation', models.CharField(max_length=100)),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.User')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheive', models.FloatField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.User')),
            ],
        ),
    ]
