# Generated by Django 2.2.7 on 2019-11-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyze.User'),
        ),
    ]
