# Generated by Django 2.2.7 on 2019-11-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_auto_20191114_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='skill',
            field=models.FloatField(null=True),
        ),
    ]
