# Generated by Django 2.2.5 on 2019-11-18 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0005_remove_score_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='score',
            name='skill',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
