# Generated by Django 2.2.5 on 2019-11-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0006_auto_20191118_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
